<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 */
function couch_api_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'repository') {
    \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
  }
}

/**
 * Implements hook_entity_update().
 */
function couch_api_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'repository') {
    \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
  }
}

/**
 * Implements hook_entity_delete().
 */
function couch_api_entity_delete(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'repository') {
    \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
  }
}
