<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;

/**
 * Implements hook_entity_insert().
 */
function relaxed_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'workspace') {
    // In some cases (mostly testing) the plugin manager is not yet initialized.
    // @todo {@link https://www.drupal.org/node/2599864 Fix this.}
    try {
      \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
    }
    catch (InvalidArgumentException $e) {
      watchdog_exception('relaxed', $e);
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function relaxed_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'workspace') {
    // In some cases (mostly testing) the plugin manager is not yet initialized.
    // @todo {@link https://www.drupal.org/node/2599864 Fix this.}
    try {
      \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
    }
    catch (InvalidArgumentException $e) {
      watchdog_exception('relaxed', $e);
    }
  }
}

/**
 * Implements hook_entity_delete().
 */
function relaxed_entity_delete(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'workspace') {
    // In some cases (mostly testing) the plugin manager is not yet initialized.
    // @todo {@link https://www.drupal.org/node/2599864 Fix this.}
    try {
      \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
    }
    catch (InvalidArgumentException $e) {
      watchdog_exception('relaxed', $e);
    }
  }
}

/**
 * Implements hook_entity_access().
 */
function relaxed_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  /** @var \Drupal\multiversion\MultiversionManagerInterface $manager */
  $multiversion_manager = \Drupal::service('multiversion.manager');
  $entity_type = $entity->getEntityType();
  $entity_type_id = $entity_type->id();

  if ($multiversion_manager->isEnabledEntityType($entity_type) || $entity_type_id == 'replication_log') {
    return AccessResult::allowedIfHasPermission($account, 'perform content replication');
  }

  // No opinion.
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_create_access().
 */
function multiversion_entity_create_access(AccountInterface $account, array $context, $entity_bundle) {
  /** @var \Drupal\multiversion\MultiversionManagerInterface $manager */
  $multiversion_manager = \Drupal::service('multiversion.manager');
  $bundles_info = \Drupal::entityManager()->getAllBundleInfo();
  foreach ($bundles_info as $entity_type_id => $bundles) {
    if (in_array($entity_bundle, array_keys($bundles))) {
      $entity_type = \Drupal::entityManager()->getDefinition($entity_type_id);
      if ($multiversion_manager->isEnabledEntityType($entity_type) || $entity_type_id == 'replication_log') {
        return AccessResult::allowedIfHasPermission($account, 'perform content replication');
      }
    }
  }

  // No opinion.
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_field_access().
 */
function relaxed_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  return AccessResult::allowedIfHasPermission($account, 'perform content replication');
}
