<?php

use Drupal\Component\Utility\Random;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\taxonomy\TermStorageInterface;
use Drupal\user\UserStorageInterface;
use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;

/**
 * Implements hook_entity_insert().
 */
function relaxed_entity_insert(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'workspace') {
    // In some cases (mostly testing) the plugin manager is not yet initialized.
    // @todo Fix this.
    try {
      \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
    }
    catch (InvalidArgumentException $e) {
      watchdog_exception('relaxed', $e);
    }
  }
}

/**
 * Implements hook_entity_update().
 */
function relaxed_entity_update(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'workspace') {
    // In some cases (mostly testing) the plugin manager is not yet initialized.
    // @todo Fix this.
    try {
      \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
    }
    catch (InvalidArgumentException $e) {
      watchdog_exception('relaxed', $e);
    }
  }
}

/**
 * Implements hook_entity_delete().
 */
function relaxed_entity_delete(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == 'workspace') {
    // In some cases (mostly testing) the plugin manager is not yet initialized.
    // @todo Fix this.
    try {
      \Drupal::service('plugin.manager.rest')->clearCachedDefinitions();
    }
    catch (InvalidArgumentException $e) {
      watchdog_exception('relaxed', $e);
    }
  }
}

/**
 * Implements hook_entity_access().
 */
function relaxed_entity_access(EntityInterface $entity, $operation, AccountInterface $account, $langcode) {
  /** @var \Drupal\multiversion\MultiversionManagerInterface $manager */
  $multiversion_manager = \Drupal::service('multiversion.manager');
  $entity_type = $entity->getEntityType();
  $entity_type_id = $entity_type->id();

  if ($multiversion_manager->isSupportedEntityType($entity_type) || $entity_type_id == 'replication_log') {
    return AccessResult::allowedIfHasPermission($account, 'perform content replication');
  }

  // No opinion.
  return AccessResult::neutral();
}

/**
 * Implements hook_entity_field_access().
 */
function relaxed_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  return AccessResult::allowedIfHasPermission($account, 'perform content replication');
}

/**
 * Implements hook_entity_create_stub().
 */
function relaxed_entity_create_stub(EntityStorageInterface $target_storage) {
  $target_entity_values = array();

  if ($target_storage instanceof TermStorageInterface) {
    $target_entity_values['vid'] = 'tags';
    $target_entity_values['name'] = 'Stub name for taxonomy term';
  }

  if ($target_storage instanceof UserStorageInterface) {
    $random = new Random();
    $target_entity_values['name'] = $random->name(8, TRUE);
  }

  return $target_entity_values;
}
